version: "3.8"
services:

  app:
    build:
      context: ${PROJECT_DIR}
      dockerfile: images/Dockerfile
    container_name: query_tag_prediction
    image: query_tag_prediction
    volumes:
      - ${PROJECT_DIR}/:/app
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - .env
